




 services:
   spartan-db-container:
     env_file:
       - .env_db
     ports:
       - '5436:5432'
     restart: always
   spartan-app-container:
     env_file:
       - .env_app
     ports:
       - '8000:8000'

